(function(){
  'use strict';
  var home=document.getElementById('home'),player=document.getElementById('playerView');
  var input=document.getElementById('channel'),watch=document.getElementById('watch');
  var results=document.getElementById('results'),searchSection=document.getElementById('searchSection'),searchState=document.getElementById('searchState');
  var recent=document.getElementById('recent'),recentSection=document.getElementById('recentSection');
  var chatPanel=document.getElementById('chatPanel'),chatMessages=document.getElementById('chatMessages'),chatStatus=document.getElementById('chatStatus');
  var qualityMenu=document.getElementById('qualityMenu'),qualityOptions=document.getElementById('qualityOptions');
  var history=[],playing=false,current='',displayName='',streamUrl='',roomId=null,chatVisible=false;
  var selectedQuality='auto',qualityOpen=false,qualityCursor=0;
  var searchTimer=null,searchSequence=0,requestSequence=0,avSequence=0,offlineTimer=null,hudTimer=null;
  var chatSocket=null,chatReconnect=null,secret=[];
  var pusherUrl='wss://ws-us2.pusher.com/app/32cbd69e4b950bf97679?protocol=7&client=js&version=8.4.0&flash=false';
  var language=/^(cs|cz|ces)(-|_|$)/i.test(navigator.language||'')?'cs':'en';
  var text={
    cs:{ready:'Připraveno pro starší TV',headline:'Kick pohodlně i na starší televizi.',subline:'Jednoduché přehrávání a živý chat bez zbytečné zátěže.',find:'Najít streamera',findHelp:'Stačí část jména nebo adresa kanálu',placeholder:'Jméno streamera…',watch:'Sledovat',searchTip:'Z textového pole odejdeš šipkou doprava nebo dolů.',results:'Výsledky hledání',recent:'Naposledy sledované',select:'vybrat',back:'zpět',loading:'Načítám stream…',playerHint:'↑ kvalita · OK chat · Zpět výběr',chat:'Živý chat',connecting:'Připojuji…',connected:'Připojeno',reconnecting:'Obnovuji spojení…',chatUnavailable:'Chat není dostupný',empty:'Nové zprávy se objeví tady.',hideChat:'skrýt chat',showChat:'↑ kvalita · OK zobrazit chat · Zpět výběr',quality:'Kvalita obrazu',qualityHelp:'Šipkami vyber · OK potvrď · Zpět zavři',automatic:'Automaticky',saved:'zvoleno',changing:'Měním kvalitu…',compatibility:'Starší TV odmítla profil kvality. Zkouším automatický režim.',checking:'ověřuji…',unknown:'neznámý stav',followers:'sledujících',viewers:'diváků',exact:'Přesně zadaný kanál',onlineCheck:'hledám online…',localOnly:'lokální výsledek',getting:'Získávám stream…',api:'Připojuji se ke Kicku.',offline:'{name} je offline',offlineDetail:'Každých 10 sekund kontroluji, jestli vysílání nezačalo.',starting:'{name} je online',startingDetail:'Spouštím živý přenos…',loadingVideo:'Načítám obraz…',buffering:'TV načítá první data.',ended:'Vysílání skončilo',endedDetail:'Čekám, jestli streamer znovu začne.',cannotPlay:'Stream se nepodařilo spustit',network:'Kick neodpovídá',networkDetail:'Zkontroluj připojení a zkus to znovu.',avMissing:'AVPlay není dostupný',avMissingDetail:'Tato televize neposkytla přehrávač Samsung AVPlay.'},
    en:{ready:'Ready for older TVs',headline:'Kick comfortably, even on an older TV.',subline:'Simple playback and live chat without unnecessary load.',find:'Find a streamer',findHelp:'Enter part of a name or a channel address',placeholder:'Streamer name…',watch:'Watch',searchTip:'Leave the text field with Right or Down.',results:'Search results',recent:'Recently watched',select:'select',back:'back',loading:'Loading stream…',playerHint:'↑ quality · OK chat · Back channels',chat:'Live chat',connecting:'Connecting…',connected:'Connected',reconnecting:'Reconnecting…',chatUnavailable:'Chat is unavailable',empty:'New messages will appear here.',hideChat:'hide chat',showChat:'↑ quality · OK show chat · Back channels',quality:'Video quality',qualityHelp:'Use arrows · OK apply · Back close',automatic:'Automatic',saved:'selected',changing:'Changing quality…',compatibility:'The older TV rejected this quality profile. Trying automatic mode.',checking:'checking…',unknown:'unknown status',followers:'followers',viewers:'viewers',exact:'Exact channel name',onlineCheck:'searching online…',localOnly:'local result',getting:'Getting stream…',api:'Connecting to Kick.',offline:'{name} is offline',offlineDetail:'Checking every 10 seconds whether the stream has started.',starting:'{name} is live',startingDetail:'Starting the live stream…',loadingVideo:'Loading video…',buffering:'The TV is buffering the first data.',ended:'Stream ended',endedDetail:'Waiting for the streamer to return.',cannotPlay:'Unable to start the stream',network:'Kick did not respond',networkDetail:'Check the connection and try again.',avMissing:'AVPlay is unavailable',avMissingDetail:'This TV did not provide Samsung AVPlay.'}
  };
  var qualities=[
    {id:'auto',labelKey:'automatic',adaptive:''},
    {id:'1080',label:'1080p',adaptive:'BITRATES=5000~9000|STARTBITRATE=HIGHEST'},
    {id:'720',label:'720p',adaptive:'BITRATES=2000~4999|STARTBITRATE=HIGHEST'},
    {id:'480',label:'480p',adaptive:'BITRATES=900~1999|STARTBITRATE=HIGHEST'},
    {id:'360',label:'360p',adaptive:'BITRATES=400~899|STARTBITRATE=HIGHEST'}
  ];
  function tr(key,values){var value=(text[language]&&text[language][key])||text.en[key]||key;values=values||{};return value.replace(/\{(\w+)\}/g,function(all,name){return values[name]===undefined?'':values[name];});}
  function applyLanguage(){var nodes=document.querySelectorAll('[data-i18n]'),i;document.documentElement.lang=language;for(i=0;i<nodes.length;i++){if(nodes[i].getAttribute('data-i18n')==='headline')nodes[i].innerHTML=tr('headline').replace(', ','<br>');else nodes[i].textContent=tr(nodes[i].getAttribute('data-i18n'));}nodes=document.querySelectorAll('[data-i18n-placeholder]');for(i=0;i<nodes.length;i++)nodes[i].setAttribute('placeholder',tr(nodes[i].getAttribute('data-i18n-placeholder')));}
  function clean(value){value=String(value||'').trim().toLowerCase();value=value.replace(/^https?:\/\/(www\.)?kick\.com\//,'').replace(/[?#].*$/,'').replace(/^@/,'');return value.replace(/[^a-z0-9_-]/g,'');}
  function safe(value){return String(value||'').replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function compact(value){var n=Number(value)||0;return n>=1000000?(n/1000000).toFixed(1)+'M':n>=1000?Math.round(n/1000)+'K':String(n);}
  function channelName(data,fallback){return String(data&&data.user&&data.user.username||data&&data.username||fallback||'Kick');}
  function category(data){var live=data&&data.livestream||{},item=live.category||(live.categories&&live.categories[0])||data&&data.category;return String(item&&(item.name||item.title)||'');}
  function setStatus(title,detail,error){document.getElementById('statusTitle').textContent=title;document.getElementById('statusDetail').textContent=detail||'';player.classList.remove('player-ready');if(error)player.classList.add('player-error');else player.classList.remove('player-error');}
  function qualityIndex(id){var i;for(i=0;i<qualities.length;i++)if(qualities[i].id===id)return i;return 0;}
  function currentQuality(){return qualities[qualityIndex(selectedQuality)];}
  function qualityLabel(item){return item.label||tr(item.labelKey);}
  function updateNowPlaying(){document.getElementById('nowPlaying').textContent='kick.com/'+current+(player.classList.contains('offline-state')?' · OFFLINE':' · '+qualityLabel(currentQuality()));}
  function showHud(){player.classList.add('hud');clearTimeout(hudTimer);hudTimer=setTimeout(function(){player.classList.remove('hud');},2300);}
  function renderHistory(){var i;recent.innerHTML='';recentSection.className=history.length?'section':'section hidden';for(i=0;i<history.length;i++)addHistory(history[i]);}
  function addHistory(name){var button=document.createElement('button'),title=document.createElement('strong'),meta=document.createElement('span');button.className='history-item focusable';title.textContent=name;meta.className='meta';meta.textContent=tr('checking');button.appendChild(title);button.appendChild(meta);button.onclick=function(){openChannel(name);};recent.appendChild(button);refreshStatus(name,meta);}
  function refreshStatus(name,meta){var xhr=new XMLHttpRequest();xhr.open('GET','https://kick.com/api/v2/channels/'+encodeURIComponent(name),true);xhr.timeout=7000;xhr.onreadystatechange=function(){if(xhr.readyState!==4)return;if(xhr.status>=200&&xhr.status<300){try{var data=JSON.parse(xhr.responseText),live=!!(data.livestream&&data.livestream.is_live!==false),viewers=Number(data.livestream&&data.livestream.viewer_count)||0,cat=category(data);meta.className='meta '+(live?'live':'offline');meta.textContent=live?'● LIVE · '+compact(viewers)+' '+tr('viewers')+(cat?' · '+cat:''):'○ OFFLINE';}catch(e){meta.textContent=tr('unknown');}}else meta.textContent=tr('unknown');};xhr.onerror=function(){meta.textContent=tr('unknown');};xhr.ontimeout=xhr.onerror;try{xhr.send();}catch(e){meta.textContent=tr('unknown');}}
  function renderResults(items){var i;results.innerHTML='';searchSection.className=items.length?'section':'section hidden';for(i=0;i<items.length&&i<6;i++)addResult(items[i]);}
  function addResult(item){var button=document.createElement('button'),name=item.username||item.slug,status=item.is_live?'● LIVE':'○ OFFLINE';button.className='result focusable';button.innerHTML='<strong>'+safe(name)+'</strong><span class="meta '+(item.is_live?'live':'offline')+'">'+status+' · '+safe(item.category&&item.category.name||'Kick')+(item.followers_count?' · '+compact(item.followers_count)+' '+tr('followers'):'')+'</span>';button.onclick=function(){openChannel(item.slug);};results.appendChild(button);}
  function fallback(raw){var slug=clean(raw);return slug?{slug:slug,username:String(raw||slug).replace(/^@/,''),is_live:false,followers_count:0,category:{name:tr('exact')}}:null;}
  function search(raw){var query=String(raw||'').trim();clearTimeout(searchTimer);if(query.length<2){renderResults([]);searchState.textContent='';return;}searchTimer=setTimeout(function(){var seq=++searchSequence,xhr=new XMLHttpRequest(),done=false,initial=fallback(query);if(initial)renderResults([initial]);searchState.textContent=tr('onlineCheck');function finish(items,label){if(done||seq!==searchSequence)return;done=true;if(!items.length&&initial)items=[initial];renderResults(items);searchState.textContent=label||'';}xhr.open('GET','https://www.kickstats.com/api/search?query='+encodeURIComponent(query),true);xhr.timeout=6000;xhr.onreadystatechange=function(){if(xhr.readyState===4){if(xhr.status>=200&&xhr.status<300)try{finish(JSON.parse(xhr.responseText).channels||[],'');}catch(e){finish([],tr('localOnly'));}else finish([],tr('localOnly'));}};xhr.onerror=function(){finish([],tr('localOnly'));};xhr.ontimeout=xhr.onerror;try{xhr.send();}catch(e){finish([],tr('localOnly'));}setTimeout(function(){finish([],tr('localOnly'));},6500);},350);}
  function clearChat(){chatMessages.innerHTML='<div class="empty">'+safe(tr('empty'))+'</div>';setChatState(tr('connecting'),false);}
  function setChatState(label,connected){chatStatus.textContent=label;if(connected)chatPanel.classList.add('chat-connected');else chatPanel.classList.remove('chat-connected');}
  function toggleChat(show){chatVisible=show===undefined?!chatVisible:!!show;if(chatVisible)player.classList.add('chat-open');else player.classList.remove('chat-open');document.getElementById('hint').textContent=chatVisible?tr('playerHint'):tr('showChat');showHud();}
  function renderQuality(){var i,item,row,label,state;qualityOptions.innerHTML='';for(i=0;i<qualities.length;i++){item=qualities[i];row=document.createElement('div');label=document.createElement('strong');state=document.createElement('span');row.className='quality-option'+(i===qualityCursor?' focused':'')+(item.id===selectedQuality?' selected':'');label.textContent=qualityLabel(item);state.textContent=item.id===selectedQuality?tr('saved'):'';row.appendChild(label);row.appendChild(state);qualityOptions.appendChild(row);}}
  function openQuality(){if(!streamUrl)return;qualityCursor=qualityIndex(selectedQuality);qualityOpen=true;player.classList.add('quality-open');renderQuality();}
  function closeQuality(){qualityOpen=false;player.classList.remove('quality-open');showHud();}
  function moveQuality(delta){qualityCursor=(qualityCursor+delta+qualities.length)%qualities.length;renderQuality();}
  function applyQuality(){selectedQuality=qualities[qualityCursor].id;try{localStorage.setItem('kicktv.lite.quality',selectedQuality);}catch(e){}closeQuality();updateNowPlaying();if(streamUrl){setStatus(tr('changing'),' ',false);startAV(streamUrl,false);}}
  function emotesAsText(value){return String(value||'').replace(/\[emote:\d+:([^\]]+)\]/g,':$1:');}
  function addMessage(data){var sender=data.sender||data.user||{},content=data.content||(data.message&&data.message.message)||'',username=sender.username||'Kick',empty,item,name,message,color='';if(!content)return;empty=chatMessages.querySelector('.empty');if(empty&&empty.parentNode)empty.parentNode.removeChild(empty);item=document.createElement('div');name=document.createElement('span');message=document.createElement('span');item.className='message';name.className='name';name.textContent=username;message.textContent=emotesAsText(content);color=sender.identity&&sender.identity.color;if(/^#[0-9a-f]{6}$/i.test(color||''))name.style.color=color;item.appendChild(name);item.appendChild(message);chatMessages.appendChild(item);while(chatMessages.children.length>36)chatMessages.removeChild(chatMessages.firstChild);chatMessages.scrollTop=chatMessages.scrollHeight;}
  function disconnectChat(){clearTimeout(chatReconnect);chatReconnect=null;var socket=chatSocket;chatSocket=null;if(socket)try{socket.close();}catch(e){}}
  function connectChat(id){disconnectChat();roomId=id;if(!id){setChatState(tr('chatUnavailable'),false);return;}setChatState(tr('connecting'),false);try{var socket=new WebSocket(pusherUrl);chatSocket=socket;socket.onmessage=function(event){if(socket!==chatSocket)return;try{var packet=JSON.parse(event.data),payload=typeof packet.data==='string'?JSON.parse(packet.data):packet.data;if(packet.event==='pusher:connection_established')socket.send(JSON.stringify({event:'pusher:subscribe',data:{auth:'',channel:'chatrooms.'+id+'.v2'}}));else if(packet.event==='pusher_internal:subscription_succeeded')setChatState(tr('connected'),true);else if(packet.event==='pusher:ping')socket.send(JSON.stringify({event:'pusher:pong',data:{}}));else if(packet.event&&packet.event.indexOf('ChatMessage')>=0)addMessage(payload||{});}catch(e){}};socket.onerror=function(){if(socket===chatSocket)setChatState(tr('reconnecting'),false);};socket.onclose=function(){if(socket!==chatSocket||!playing)return;chatSocket=null;setChatState(tr('reconnecting'),false);chatReconnect=setTimeout(function(){if(playing)connectChat(id);},4000);};}catch(e){setChatState(tr('chatUnavailable'),false);}}
  function stopAV(){avSequence++;if(!window.webapis||!webapis.avplay)return;try{var state=webapis.avplay.getState();if(state==='PLAYING'||state==='PAUSED'||state==='READY')webapis.avplay.stop();if(webapis.avplay.getState()!=='NONE')webapis.avplay.close();}catch(e){}}
  function revealVideo(){player.classList.add('player-ready');document.documentElement.classList.add('video-playing');document.body.classList.add('video-playing');}
  function startAV(url,skipAdaptive){
    if(!window.webapis||!webapis.avplay){setStatus(tr('avMissing'),tr('avMissingDetail'),true);return;}
    var attempt=0,adaptiveApplied=false,item=currentQuality();
    function active(){return playing&&streamUrl===url&&attempt===avSequence;}
    function failed(error){
      if(!active())return;
      if(!skipAdaptive&&adaptiveApplied){setStatus(tr('changing'),tr('compatibility'),false);setTimeout(function(){if(active())startAV(url,true);},140);return;}
      setStatus(tr('cannotPlay'),String(error&&error.message||error||tr('unknown')),true);
    }
    try{
      stopAV();attempt=++avSequence;webapis.avplay.open(url);webapis.avplay.setDisplayRect(0,0,1920,1080);webapis.avplay.setDisplayMethod('PLAYER_DISPLAY_MODE_LETTER_BOX');
      if(!skipAdaptive&&item.adaptive)try{webapis.avplay.setStreamingProperty('ADAPTIVE_INFO',item.adaptive);adaptiveApplied=true;}catch(ignoreAdaptive){}
      webapis.avplay.setListener({onbufferingstart:function(){if(active())setStatus(tr('loadingVideo'),tr('buffering'),false);},onbufferingprogress:function(percent){if(active())document.getElementById('statusDetail').textContent='Buffer '+percent+' %';},onbufferingcomplete:function(){if(active()){revealVideo();showHud();}},oncurrentplaytime:function(){if(active())revealVideo();},onstreamcompleted:function(){if(active())showOffline();},onerror:function(error){if(active())setStatus(tr('cannotPlay'),String(error&&error.message||error||tr('unknown')),true);},onevent:function(){},onsubtitlechange:function(){},ondrmevent:function(){}});
      webapis.avplay.prepareAsync(function(){if(!active())return;try{webapis.avplay.play();}catch(e){failed(e);}},failed);
    }catch(e){failed(e);}
  }
  function scheduleCheck(){clearTimeout(offlineTimer);offlineTimer=setTimeout(function(){if(playing)requestStream(true);},10000);}
  function showOffline(){if(!playing)return;stopAV();streamUrl='';document.documentElement.classList.remove('video-playing');document.body.classList.remove('video-playing');player.classList.remove('player-ready','player-error');player.classList.add('offline-state');setStatus(tr('offline',{name:displayName||current}),tr('offlineDetail'),false);toggleChat(true);updateNowPlaying();scheduleCheck();}
  function requestStream(polling){var seq=++requestSequence,xhr=new XMLHttpRequest();xhr.open('GET','https://kick.com/api/v2/channels/'+encodeURIComponent(current),true);xhr.timeout=12000;xhr.setRequestHeader('Accept','application/json');function active(){return playing&&seq===requestSequence;}function failed(){if(!active())return;if(polling&&player.classList.contains('offline-state'))scheduleCheck();else setStatus(tr('network'),tr('networkDetail'),true);}xhr.onreadystatechange=function(){if(xhr.readyState!==4||!active())return;if(xhr.status>=200&&xhr.status<300)try{var data=JSON.parse(xhr.responseText),live=!!(data.livestream&&data.livestream.is_live!==false&&data.playback_url);displayName=channelName(data,current);if(!live){if(!chatSocket)connectChat(data.chatroom&&data.chatroom.id);showOffline();return;}clearTimeout(offlineTimer);streamUrl=data.playback_url;player.classList.remove('offline-state','player-error');setStatus(tr('starting',{name:displayName}),tr('startingDetail'),false);updateNowPlaying();if(!chatSocket)connectChat(data.chatroom&&data.chatroom.id);startAV(streamUrl);}catch(e){failed();}else failed();};xhr.onerror=failed;xhr.ontimeout=failed;try{xhr.send();}catch(e){failed();}}
  function openChannel(raw){var name=clean(raw),i;if(!name){input.focus();return;}history=[name];try{var old=JSON.parse(localStorage.getItem('kicktv.lite.recent')||'[]');for(i=0;i<old.length&&history.length<5;i++)if(clean(old[i])!==name)history.push(clean(old[i]));localStorage.setItem('kicktv.lite.recent',JSON.stringify(history));}catch(e){}renderHistory();current=name;displayName=name;playing=true;streamUrl='';qualityOpen=false;document.documentElement.classList.remove('video-playing');document.body.classList.remove('video-playing');home.classList.add('hidden');player.className='';clearChat();toggleChat(false);setStatus(tr('getting'),tr('api'),false);updateNowPlaying();setScreenSaver(false);requestStream(false);}
  function closePlayer(){clearTimeout(offlineTimer);requestSequence++;disconnectChat();stopAV();playing=false;current='';streamUrl='';qualityOpen=false;document.documentElement.classList.remove('video-playing');document.body.classList.remove('video-playing');player.className='hidden';home.classList.remove('hidden');setScreenSaver(true);renderHistory();setTimeout(function(){watch.focus();},60);}
  function setScreenSaver(enabled){try{if(window.webapis&&webapis.appcommon){var state=enabled?webapis.appcommon.AppCommonScreenSaverState.SCREEN_SAVER_ON:webapis.appcommon.AppCommonScreenSaverState.SCREEN_SAVER_OFF;webapis.appcommon.setScreenSaver(state,function(){},function(){});}}catch(e){}}
  function focusables(){var nodes=document.querySelectorAll('#home .focusable'),out=[],i;for(i=0;i<nodes.length;i++)if(nodes[i].offsetWidth||nodes[i].offsetHeight)out.push(nodes[i]);return out;}
  function move(delta){var list=focusables(),i=list.indexOf(document.activeElement);if(!list.length)return;i=i<0?0:(i+delta+list.length)%list.length;list[i].focus();}
  function back(event){if(event){event.preventDefault();event.stopPropagation();}if(playing){if(qualityOpen)closeQuality();else if(chatVisible)toggleChat(false);else closePlayer();return;}if(input.value||!searchSection.classList.contains('hidden')){input.value='';renderResults([]);searchState.textContent='';input.focus();return;}try{tizen.application.getCurrentApplication().exit();}catch(e){window.close();}}
  function sparkle(){var box=document.getElementById('sparkles'),i;for(i=0;i<18;i++){var dot=document.createElement('i');dot.className='spark';dot.style.left=(20+Math.random()*60)+'%';dot.style.top=(20+Math.random()*60)+'%';dot.style.animationDelay=(Math.random()*.4)+'s';box.appendChild(dot);setTimeout((function(node){return function(){if(node.parentNode)node.parentNode.removeChild(node);};})(dot),2100);}}
  function remember(code){secret.push(code);if(secret.length>8)secret.shift();if(secret.join(',')==='38,38,40,40,37,39,37,39')sparkle();}
  try{history=JSON.parse(localStorage.getItem('kicktv.lite.recent')||'[]');selectedQuality=localStorage.getItem('kicktv.lite.quality')||'auto';if(qualities[qualityIndex(selectedQuality)].id!==selectedQuality)selectedQuality='auto';}catch(e){history=[];selectedQuality='auto';}applyLanguage();renderHistory();watch.onclick=function(){openChannel(input.value);};input.addEventListener('input',function(){search(input.value);});document.addEventListener('keydown',function(e){remember(e.keyCode);if(e.keyCode===10009||e.keyCode===27){back(e);return;}if(playing){showHud();if(qualityOpen){if(e.keyCode===38){e.preventDefault();moveQuality(-1);}else if(e.keyCode===40){e.preventDefault();moveQuality(1);}else if(e.keyCode===13){e.preventDefault();applyQuality();}return;}if(e.keyCode===38){e.preventDefault();openQuality();return;}if(e.keyCode===13){e.preventDefault();toggleChat();return;}try{if(window.webapis&&webapis.avplay){var state=webapis.avplay.getState();if(e.keyCode===415&&state!=='PLAYING')webapis.avplay.play();else if(e.keyCode===19&&state==='PLAYING')webapis.avplay.pause();else if(e.keyCode===10252){if(state==='PLAYING')webapis.avplay.pause();else if(state==='PAUSED')webapis.avplay.play();}}}catch(ignore){}return;}if(document.activeElement===input){if(e.keyCode===39||e.keyCode===40){e.preventDefault();watch.focus();}else if(e.keyCode===13){e.preventDefault();search(input.value);setTimeout(function(){var first=results.querySelector('.focusable');if(first)first.focus();else watch.focus();},500);}return;}if(e.keyCode===37||e.keyCode===38){e.preventDefault();move(-1);}else if(e.keyCode===39||e.keyCode===40){e.preventDefault();move(1);}else if(e.keyCode===13&&document.activeElement)document.activeElement.click();},true);try{['MediaPlay','MediaPause','MediaPlayPause'].forEach(function(key){tizen.tvinputdevice.registerKey(key);});}catch(e){}setTimeout(function(){input.focus();},100);
})();
